apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: maas-gateway
  namespace: maas-gateway
spec:
  gatewayClassName: openshift-ai-inference
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: maas-gateway-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - rhaiis-demo